-- Catálogo de marcas y modelos de vehículo (los más comunes en México), para los
-- selectores de Ventas y Trabajos. "Otra marca" / "Otro modelo" se captura como
-- texto libre en el formulario y no depende de este catálogo.
-- Importa forzando utf8mb4: mysql --default-character-set=utf8mb4 -u root taller < 006_vehiculos_catalogo.sql
USE taller;

CREATE TABLE IF NOT EXISTS vehiculo_marcas (
    id     INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(60) NOT NULL UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS vehiculo_modelos (
    id        INT AUTO_INCREMENT PRIMARY KEY,
    marca_id  INT NOT NULL,
    nombre    VARCHAR(80) NOT NULL,
    CONSTRAINT fk_vehiculo_modelo_marca FOREIGN KEY (marca_id) REFERENCES vehiculo_marcas(id) ON DELETE CASCADE,
    INDEX idx_vehiculo_modelos_marca (marca_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO vehiculo_marcas (nombre) VALUES
('Nissan'),
('Chevrolet'),
('Volkswagen'),
('Toyota'),
('Kia'),
('Honda'),
('Ford'),
('Mazda'),
('Hyundai'),
('Suzuki'),
('Renault'),
('Seat'),
('Fiat'),
('Jeep'),
('RAM'),
('Dodge'),
('Chrysler'),
('BMW'),
('Mercedes-Benz'),
('Audi'),
('Mitsubishi'),
('Peugeot'),
('GMC'),
('Subaru'),
('Isuzu'),
('Changan'),
('JAC'),
('Chirey');

INSERT INTO vehiculo_modelos (marca_id, nombre) VALUES
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Nissan'), 'Versa'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Nissan'), 'Sentra'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Nissan'), 'Altima'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Nissan'), 'March'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Nissan'), 'Kicks'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Nissan'), 'X-Trail'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Nissan'), 'Frontier'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Nissan'), 'NP300'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Nissan'), 'Tsuru'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Nissan'), 'Note'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Nissan'), 'Pathfinder'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Nissan'), 'Murano'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Nissan'), 'Platina'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Chevrolet'), 'Aveo'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Chevrolet'), 'Spark'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Chevrolet'), 'Onix'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Chevrolet'), 'Beat'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Chevrolet'), 'Sonic'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Chevrolet'), 'Cruze'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Chevrolet'), 'Malibu'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Chevrolet'), 'Cavalier'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Chevrolet'), 'Silverado'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Chevrolet'), 'Tahoe'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Chevrolet'), 'Suburban'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Chevrolet'), 'Trax'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Chevrolet'), 'Equinox'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Chevrolet'), 'Captiva'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Chevrolet'), 'S10'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Volkswagen'), 'Jetta'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Volkswagen'), 'Vento'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Volkswagen'), 'Gol'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Volkswagen'), 'Golf'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Volkswagen'), 'Polo'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Volkswagen'), 'Tiguan'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Volkswagen'), 'T-Cross'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Volkswagen'), 'Virtus'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Volkswagen'), 'Saveiro'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Volkswagen'), 'Amarok'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Volkswagen'), 'Bora'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Volkswagen'), 'Passat'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Volkswagen'), 'Crossfox'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Volkswagen'), 'Pointer'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Volkswagen'), 'Sedán (Vocho)'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Toyota'), 'Corolla'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Toyota'), 'Yaris'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Toyota'), 'Camry'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Toyota'), 'RAV4'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Toyota'), 'Hilux'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Toyota'), 'Tacoma'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Toyota'), 'Land Cruiser'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Toyota'), 'Prius'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Toyota'), 'Avanza'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Toyota'), 'Sienna'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Toyota'), '4Runner'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Toyota'), 'Highlander'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Toyota'), 'C-HR'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Toyota'), 'Tundra'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Kia'), 'Rio'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Kia'), 'Forte'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Kia'), 'Sportage'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Kia'), 'Sorento'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Kia'), 'Soul'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Kia'), 'Picanto'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Kia'), 'Seltos'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Kia'), 'Stonic'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Kia'), 'Sonet'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Kia'), 'K3'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Kia'), 'Cerato'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Honda'), 'Civic'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Honda'), 'Accord'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Honda'), 'CR-V'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Honda'), 'HR-V'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Honda'), 'Fit'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Honda'), 'City'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Honda'), 'Pilot'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Honda'), 'Odyssey'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Honda'), 'BR-V'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Ford'), 'Fiesta'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Ford'), 'Focus'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Ford'), 'Figo'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Ford'), 'Explorer'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Ford'), 'Escape'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Ford'), 'Edge'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Ford'), 'F-150'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Ford'), 'Ranger'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Ford'), 'EcoSport'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Ford'), 'Mustang'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Ford'), 'Lobo'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Ford'), 'Expedition'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Mazda'), 'Mazda2'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Mazda'), 'Mazda3'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Mazda'), 'Mazda6'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Mazda'), 'CX-3'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Mazda'), 'CX-5'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Mazda'), 'CX-30'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Mazda'), 'CX-9'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Mazda'), 'BT-50'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Hyundai'), 'Accent'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Hyundai'), 'Elantra'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Hyundai'), 'Tucson'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Hyundai'), 'Santa Fe'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Hyundai'), 'Grand i10'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Hyundai'), 'Creta'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Hyundai'), 'Venue'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Hyundai'), 'Kona'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Suzuki'), 'Swift'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Suzuki'), 'Vitara'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Suzuki'), 'Ignis'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Suzuki'), 'S-Cross'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Suzuki'), 'Ciaz'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Suzuki'), 'Jimny'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Renault'), 'Logan'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Renault'), 'Sandero'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Renault'), 'Stepway'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Renault'), 'Duster'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Renault'), 'Kwid'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Renault'), 'Captur'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Renault'), 'Kangoo'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Seat'), 'Ibiza'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Seat'), 'León'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Seat'), 'Toledo'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Seat'), 'Arona'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Seat'), 'Ateca'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Fiat'), 'Uno'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Fiat'), 'Palio'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Fiat'), 'Argo'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Fiat'), 'Mobi'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Fiat'), 'Pulse'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Fiat'), '500'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Jeep'), 'Renegade'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Jeep'), 'Compass'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Jeep'), 'Wrangler'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Jeep'), 'Grand Cherokee'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Jeep'), 'Cherokee'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Jeep'), 'Patriot'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'RAM'), '700'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'RAM'), '1500'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'RAM'), '2500'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'RAM'), '750'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'RAM'), 'ProMaster'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Dodge'), 'Attitude'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Dodge'), 'Journey'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Dodge'), 'Durango'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Dodge'), 'Neon'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Dodge'), 'Charger'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Dodge'), 'Nitro'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Chrysler'), '200'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Chrysler'), '300'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Chrysler'), 'Town & Country'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Chrysler'), 'PT Cruiser'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'BMW'), 'Serie 1'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'BMW'), 'Serie 2'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'BMW'), 'Serie 3'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'BMW'), 'Serie 4'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'BMW'), 'Serie 5'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'BMW'), 'X1'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'BMW'), 'X3'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'BMW'), 'X5'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Mercedes-Benz'), 'Clase A'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Mercedes-Benz'), 'Clase C'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Mercedes-Benz'), 'Clase E'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Mercedes-Benz'), 'GLA'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Mercedes-Benz'), 'GLC'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Mercedes-Benz'), 'Sprinter'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Audi'), 'A3'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Audi'), 'A4'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Audi'), 'A6'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Audi'), 'Q3'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Audi'), 'Q5'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Mitsubishi'), 'Mirage'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Mitsubishi'), 'Lancer'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Mitsubishi'), 'ASX'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Mitsubishi'), 'Outlander'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Mitsubishi'), 'L200'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Mitsubishi'), 'Eclipse Cross'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Peugeot'), '208'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Peugeot'), '2008'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Peugeot'), '3008'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Peugeot'), '301'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Peugeot'), 'Partner'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'GMC'), 'Sierra'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'GMC'), 'Terrain'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'GMC'), 'Acadia'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'GMC'), 'Yukon'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Subaru'), 'Impreza'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Subaru'), 'Forester'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Subaru'), 'Outback'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Subaru'), 'XV'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Isuzu'), 'D-Max'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Isuzu'), 'Trooper'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Changan'), 'CS35'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Changan'), 'Alsvin'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Changan'), 'Eado'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'JAC'), 'JS2'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'JAC'), 'JS4'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'JAC'), 'Sei4'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'JAC'), 'S3'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Chirey'), 'Tiggo 2'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Chirey'), 'Tiggo 4'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Chirey'), 'Tiggo 7'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Chirey'), 'Tiggo 8'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Chirey'), 'Arrizo 5');

