-- Revisión final del catálogo ("que no se nos pasen modelos y marcas"): completa
-- marcas ya existentes con modelos que faltaban (Peugeot, Seat, Dodge, RAM, JAC,
-- Changan, Audi, GMC, Isuzu) y agrega marcas con presencia real en México que
-- faltaban por completo: MG, BYD, GWM (Haval/Ora/Tank), Volvo, Buick.
-- Importa forzando utf8mb4: mysql --default-character-set=utf8mb4 -u root taller < 010_vehiculos_revision_final.sql
USE taller;

INSERT INTO vehiculo_marcas (nombre) VALUES
('MG'),
('BYD'),
('GWM'),
('Volvo'),
('Buick');

INSERT INTO vehiculo_modelos (marca_id, nombre) VALUES
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Peugeot'), '206'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Peugeot'), '306'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Peugeot'), '307'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Peugeot'), '405'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Peugeot'), '407'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Peugeot'), '508'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Seat'), 'Córdoba'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Seat'), 'Marbella'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Seat'), 'Málaga'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Dodge'), 'Dakota'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'RAM'), '3500'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'JAC'), 'JS3'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'JAC'), 'JS6'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'JAC'), 'Sunray'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'JAC'), 'Sei2'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'JAC'), 'Frison T6'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'JAC'), 'Frison T8'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'JAC'), 'X8'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Changan'), 'CS55'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Changan'), 'CS75'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Changan'), 'CS95'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Changan'), 'Hunter'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Changan'), 'UNI-K'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Audi'), 'A1'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Audi'), 'A5'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Audi'), 'A8'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Audi'), 'Q2'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Audi'), 'Q7'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Audi'), 'Q8'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Audi'), 'TT'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'GMC'), 'Canyon'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'GMC'), 'Savana'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Isuzu'), 'Rodeo'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Isuzu'), 'Amigo'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'MG'), '3'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'MG'), '5'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'MG'), 'ZS'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'MG'), 'HS'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'MG'), 'RX5'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'MG'), 'GT'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'MG'), 'One'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'BYD'), 'Dolphin'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'BYD'), 'Seagull'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'BYD'), 'Han'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'BYD'), 'King'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'BYD'), 'Yuan'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'BYD'), 'Song'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'BYD'), 'Seal'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'BYD'), 'Shark'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'GWM'), 'Haval Jolion'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'GWM'), 'Haval H6'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'GWM'), 'Poer'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'GWM'), 'Ora 03'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'GWM'), 'Ora 5'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'GWM'), 'Tank 300'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'GWM'), 'Tank 500'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Volvo'), 'XC40'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Volvo'), 'XC60'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Volvo'), 'XC90'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Volvo'), 'S60'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Volvo'), 'C40'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Buick'), 'Enclave'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Buick'), 'Encore GX'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Buick'), 'Envision'),
((SELECT id FROM vehiculo_marcas WHERE nombre = 'Buick'), 'Envista');

